<?php use Application\Model\Page; ?>
<?php if ($this->page instanceof Page): ?>
    <?php if (5 == $this->col): ?>
        <a href="<?= sprintf('%s/%d', $this->url, $this->page->first) ?>" class="tl<?= $this->page->current == $this->page->first ? ' o-25' : '' ?>">&laquo;</a>
    <?php endif; ?>
    <a href="<?= $this->url ?>/<?= $this->page->prev ?>" class="tl<?= $this->page->current == $this->page->first ? ' o-25' : '' ?>">&lsaquo;</a>
    <p class="tc"><?= sprintf('%02d / %02d', $this->page->current + 1, $this->page->pages) ?></p>
    <a href="<?= $this->url ?>/<?= $this->page->next ?>" class="tr<?= $this->page->current == $this->page->last ? ' o-25' : '' ?>">&rsaquo;</a>
    <?php if (5 == $this->col): ?>
        <a href="<?= sprintf('%s/%d', $this->url, $this->page->last) ?>" class="tl<?= $this->page->current == $this->page->last ? ' o-25' : '' ?>">&raquo;</a>
    <?php endif; ?>
<?php endif; ?>
