<?= $this->partial('partial/header', ['title' => $this->namespace . ' files', 'file' => $this->file ]) ?>
<article>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Date</th>
                <th class="w-100">Filename</th>
                <th>Size</th>
            </tr>
        </thead>
        <form method="post">
            <tbody>
                <?php foreach ($this->files as $i => $file): ?>
                    <tr class="<?= basename($this->file) == $file->getFilename() ? 'a' : '' ?>">
                        <td><?= sprintf('%02d', $i) ?></td>
                        <td><?= date('Y-m-d H:i:s', $file->getCtime()) ?></td>
                        <td><?= $file->getBasename() ?></td>
                        <td class="tr"><?= sprintf('%d kB', ceil($file->getSize() / 1024)) ?></td>
                        <td class="p-0">
                            <button type="submit" name="action" value="delete,<?= $file->getBasename() ?>">delete</button>
                        </td>
                        <td class="p-0">
                            <button type="submit" name="action" value="select,<?= $file->getBasename() ?>">select</button>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </form>
        <form method="post">
            <tbody>
                <tr>
                    <td colspan="2">&nbsp;</td>
                    <td class="p-0 w-100"><input type="text" name="filename" required></td>
                    <td class="p-0">
                        <button type="submit" name="action" value="create">create</button>
                    </td>
                </tr>
            </tbody>
        </form>
    </table>
</article>
