<?= $this->partial('partial/header', ['prefix' => $this->prefix, 'action' => 'files', 'file' => $this->file ]) ?>
<article>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Date</th>
                <th class="w-100">Filename</th>
            </tr>
        </thead>
        <form method="post">
            <tbody>
                <?php foreach ($this->collection as $i => $item): ?>
                    <tr class="<?= $this->selected == $item->getBasename() ? 'a' : '' ?>">
                        <td><?= sprintf('%02d', $i) ?></td>
                        <td><?= date('Y-m-d H:i:s', $item->getCtime()) ?></td>
                        <td><?= $item->getBasename() ?></td>
                        <td class="p-0">
                            <button type="submit" name="action" value="delete,<?= $item->getBasename() ?>">delete</button>
                        </td>
                        <td class="p-0">
                            <button type="submit" name="action" value="select,<?= $item->getBasename() ?>">select</button>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </form>
        <form method="post">
            <tbody>
                <tr>
                    <td colspan="2">&nbsp;</td>
                    <td class="p-0 w-100"><input type="text" name="filename" required></td>
                    <td class="p-0">
                        <button type="submit" name="action" value="create">create</button>
                    </td>
                </tr>
            </tbody>
        </form>
    </table>
</article>
