<form method="post">
    <header class="dt h-2">
        <h2><?= sprintf('%s files', $this->prefix) ?></h2>
    </header>
    <article>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th class="w-100">Filename</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->collection as $i => $item): ?>
                    <tr class="<?= $this->selected == $item->getBasename() ? 'a' : '' ?>">
                        <td><?= sprintf('%02d', $i) ?></td>
                        <td><?= $item->getBasename() ?></td>
                        <td class="p-0">
                            <button type="submit" name="action" value="delete,<?= $item->getBasename() ?>">delete</button>
                        </td>
                        <td class="p-0">
                            <button type="submit" name="action" value="select,<?= $item->getBasename() ?>">select</button>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <td>&nbsp;</td>
                    <td class="p-0"><input type="text" name="filename"></td>
                    <td class="p-0">
                        <button type="submit" name="action" value="create">create</button>
                    </td>
                </tr>
            </tfoot>
        </table>
    </article>
</form>