<form method="post">
    <?= $this->partial('partial/header', ['title' => $this->namespace . ' create', 'file' => $this->file ]) ?>
    <article class="dg c-3">
        <label>Date</label>
        <input type="date" name="date" value="<?= date('Y-m-d') ?>" required>
        <p>&nbsp;</p>
        <label for="odometer">Odometer</label>
        <input type="number" name="odometer" min="0" value="" required>
        <p>km</p>
        <label>Volume</label>
        <input type="number" name="volume" min="0" step="0.01" value="" required>
        <p>l</p>
        <label>Amount</label>
        <input type="number" name="amount" min="0" step="0.01" value="" required>
        <p>&nbsp;</p>
        <label>Currency</label>
        <select name="currency" required>
            <?php foreach (['CHF', 'EUR', 'MAD', 'MRU'] as $currency): ?>
                <option value="<?= $currency ?>"><?= $currency ?></option>
            <?php endforeach; ?>
        </select>
        <p>&nbsp;</p>
    </article>
    <footer class="dg c-5">
        <button type="submit" name="action" value="save<?= $this->item ? ',' . $this->item->id : '' ?>">save</button>
        <a href="<?= $this->url(null, ['action' => 'index'], [], true) ?>">cancel</a>
        <a href="<?= $this->url(null, ['action' => 'grid'], [], true) ?>">grid</a>
        <a href="<?= $this->url(null, ['action' => 'file'], [], true) ?>" class="s-2">select</a>
    </footer>
</form>
