<form method="post">
    <?= $this->partial('partial/header', ['prefix' => $this->prefix, 'action' => $this->action, 'file' => $this->file ]) ?>
    <article>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Id</th>
                    <th>Date</th>
                    <th>Odometer</th>
                    <th>Volume</th>
                    <th>Amount</th>
                    <th>Currency</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->page as $i => $item): ?>
                    <tr>
                        <td><?= sprintf('%02d', $i) ?></td>
                        <td><?= $item->id ?></td>
                        <td><?= $item->date ?></td>
                        <td><?= $item->odometer ?></td>
                        <td><?= $item->volume ?></td>
                        <td><?= $item->amount ?></td>
                        <td><?= $item->currency ?></td>
                        <td class="p-0">
                            <button type="submit" name="action" value="delete,<?= $item->id ?>">delete</button>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </article>
    <footer class="dg c-3">
        <?= $this->partial('partial/pagination.phtml', ['page' => $this->page, 'url' => '/fuel/grid']) ?>
    </footer>
</form>
