<?= $this->partial('partial/header', ['title' => 'Fuel', 'file' => $this->file ]) ?>
<article class="dg c-3">
    <div class="dt">
        <div class="bg h-3 tc">
            <p class="f-3"><?= sprintf('%d', $this->calculation['volume']) ?> <small>l</small></p>
            <p class="o-25">volume &sum;</p>
        </div>
    </div>
    <div class="dt">
        <div class="bg h-3 tc">
            <p class="f-3"><?= sprintf('%d', $this->calculation['distance']) ?> <small>km</small></p>
            <p class="o-25">distance &sum;</p>
        </div>
    </div>
    <div class="dt">
        <div class="bg h-3 tc">
            <p class="f-3"><?= sprintf('%.01f', $this->calculation['consumption']) ?> <small>l/100km</small></p>
            <p class="o-25">volume &oslash;</p>
        </div>
    </div>
    <table class="s-3">
        <thead>
            <tr>
                <th>Date</th>
                <th>Odometer</th>
                <th>Distance</th>
                <th>Distance &sum;</th>
                <th>Volume</th>
                <th>Volume &sum;</th>
                <th>Consumption</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->page as $item): ?>
                <?php $prev = $this->page->prev($item) ?>
                <?php $first = $item === $this->page->first() ?>
                <tr>
                    <td><?= $item->date ?></td>
                    <td class="tr"><?= sprintf('%d', $item->odometer) ?></td>
                    <td class="tr"><?= sprintf('%d', $item->distance) ?></td>
                    <td class="tr"><?= sprintf('%d', $item->distance_total) ?></td>
                    <td class="tr"><?= sprintf('%d', $item->volume) ?></td>
                    <td class="tr"><?= sprintf('%d', $item->volume_total) ?></td>
                    <td class="tr"><?= sprintf('%.02f', $item->consumption) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</article>
<footer class="dg c-3">
    <?= $this->paginate($this->page) ?>
    <a href="/fuel/create">new</a>
    <a href="/fuel/grid">manage</a>
    <a href="/fuel/file">select</a>
</footer>
