<?php
use Application\Util\Coordinates;
echo $this->partial('partial/header', ['title' => $this->title, 'file' => $this->file ]);
?>
<article>
    <table>
        <thead>
            <tr>
                <th class="w-0">UTC</th>
                <th>Latitude</th>
                <th>Longitude</th>
                <th>HDOP</th>
                <th>Speed</th>
                <th>Alt</th>
                <th>Sat</th>
                <th>DGPS</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->page as $item): ?>
            <tr>
                <td><?= $item->datetime->format('Y-m-d H:i:s') ?></td>
                <td><?= sprintf('%.07f', Coordinates::gpsToDec($item->lat, $item->lat_i)) ?></td>
                <td><?= sprintf('%.07f', Coordinates::gpsToDec($item->lon, $item->lon_i)) ?></td>
                <td><?= sprintf('%.01f', $item->hdop) ?></td>
                <td><?= sprintf('%d km/h', $item->speed_m) ?></td>
                <td><?= sprintf('%d', $item->alt) ?></td>
                <td><?= sprintf('%d', $item->sat) ?></td>
                <td><?= sprintf('%d', $item->dgps) ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</article>
<footer class="dg c-5">
    <?= $this->paginate($this->page) ?>
    <p class="s-2">&nbsp;</p>
    <a href="<?= $this->url(null, ['action' => 'index'], [], true) ?>">index</a>
    <a href="<?= $this->url(null, ['action' => 'file'], [], true) ?>" class="s-2">select</a>
</footer>
