<?= $this->partial('partial/header', ['title' => $this->title, 'file' => $this->file ]) ?>
<article>
    <table>
        <thead>
            <tr>
                <th>UTC</th>
                <th>Latitude</th>
                <th>Longitude</th>
                <th>Speed</th>
                <th>Altitude</th>
                <th>Sat</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->page as $item): ?>
            <tr>
                <td><?= $item->datetime->format('Y-m-d H:i:s') ?></td>
                <td><?= sprintf('%.05f %s', $item->lat, $item->lat_i) ?></td>
                <td><?= sprintf('%.05f %s', $item->lon, $item->lon_i) ?></td>
                <td><?= sprintf('%d km/h', $item->speed_m) ?></td>
                <td><?= sprintf('%d', $item->alt) ?></td>
                <td><?= sprintf('%d', $item->sat) ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</article>
<footer class="dg c-5">
    <?= $this->paginate($this->page) ?>
</footer>
