<form method="post">
    <?= $this->partial('partial/header', ['prefix' => $this->prefix, 'action' => $this->action, 'file' => $this->file]) ?>
    <article class="dg c-3">
        <label>Date</label>
        <input type="date" name="date" value="<?= date('Y-m-d') ?>" class="s-2">
        <label>Location</label>
        <input type="text" name="location" value="" class="s-2">
        <label>Position</label>
        <input type="text" name="position" value="" class="s-2">
        <label>Headline</label>
        <input type="text" name="headline" value="" class="s-2">
        <label class="vt">Text</label>
        <textarea name="text" class="h-4 s-2"></textarea>
    </article>
    <footer class="dg c-3">
        <button type="submit" name="action" value="save">save</button>
        <p>&nbsp;</p>
        <a href="<?= $this->url('diary') ?>">cancel</a>
    </footer>
</form>
