<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('HB9HCR Mobile')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Scripts -->
    <?= $this->inlineScript()
    //->prependFile($this->basePath('js/bootstrap.min.js'))
    //->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
    ?>
    <link rel="stylesheet" href="<?= $this->basePath('css/screen.css') ?>">
    <link rel="stylesheet" href="<?= $this->basePath('css/rpi.css') ?>">
    <link rel="stylesheet" href="<?= $this->basePath('css/print.css') ?>">
</head>
<body>
<aside>
    <nav>
        <ul>
            <li><a href="/roadbook" class="active">roadbook</a></li>
            <li><a href="/route">route</a></li>
            <li><a href="/waypoint" class="active">waypoint</a></li>
            <li><a href="/log/spot">spot</a></li>
            <li><a href="/fuel">fuel</a></li>
            <li><a href="/data/band">band</a></li>
        </ul>
    </nav>
</aside>
<main>
    <?= $this->content ?>
</main>
<?= $this->inlineScript() ?>
</body>
</html>
