<form method="post">
    <?= $this->partial('partial/header', ['title' => $this->title, 'file' => $this->file ]) ?>
    <article>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Date</th>
                    <th>Region</th>
                    <th>Name</th>
                    <th>Position</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->page as $i => $item): ?>
                    <tr>
                        <td><?= sprintf('%02d', $i) ?></td>
                        <td><?= $item->date ?></td>
                        <td><?= $item->region ?></td>
                        <td><?= $item->name ?></td>
                        <td class="w-100"><?= $item->position ?></td>
                        <td class="p-0"><a href="/roadbook/index/<?= $item->id ?>" class="b">view</a></td>
                        <td class="p-0"><button type="submit" name="action" value="delete,<?= $item->id ?>">delete</button></td>
                        <td class="p-0"><button type="submit" name="action" value="move,<?= $item->id ?>,0">&uarr;</button></td>
                        <td class="p-0"><button type="submit" name="action" value="move,<?= $item->id ?>,1">&darr;</button></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </article>
    <footer class="dg c-5">
        <?= $this->paginate($this->page) ?>
        <p class="s-2">&nbsp;</p>
        <a href="/roadbook/index">index</a>
        <a href="/roadbook/file" class="s-2">select</a>
    </footer>
</form>