<form method="post">
    <?= $this->partial('partial/header', ['prefix' => $this->prefix, 'action' => $this->action, 'file' => $this->file ]) ?>
    <article>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Date</th>
                    <th>Region</th>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->page as $i => $item): ?>
                    <tr>
                        <td><?= sprintf('%02d', $i) ?></td>
                        <td><?= $item->date ?></td>
                        <td><?= $item->region ?></td>
                        <td><?= $item->name ?></td>
                        <td class="p-0"><a href="/roadbook/index/<?= $item->id ?>" class="b">view</a></td>
                        <td class="p-0"><button type="submit" name="action" value="delete,<?= $item->id ?>">delete</button></td>
                        <td class="p-0"><button type="submit" name="action" value="move,<?= $item->id ?>,0">&uarr;</button></td>
                        <td class="p-0"><button type="submit" name="action" value="move,<?= $item->id ?>,1">&darr;</button></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </article>
    <footer class="dg c-5">
        <?= $this->partial('partial/pagination.phtml', ['page' => $this->page, 'url' => '/roadbook/grid', 'col' => 5]) ?>
    </footer>
</form>