<?= $this->partial('partial/header', ['title' => $this->title, 'file' => $this->file]) ?>
<form method="post">
    <article class="dg c-3">
        <div class="dt tc">
            <div class="h-4 bg <?= $this->item->type ?>">
                <p class="f-3"><?= ceil($this->distance * .001) ?> <small>km</small></p>
                <p class="ttu"><?= $this->item->type ?></p>
            </div>
        </div>
        <table>
            <tbody>
                <tr>
                    <td>Id</td>
                    <td><?= $this->item->id ?></td>
                </tr>
                <tr>
                    <td>Date</td>
                    <td><?= $this->item->date ?></td>
                </tr>
                <tr>
                    <td>Latitude</td>
                    <td><?= $this->item->latitude ?></td>
                </tr>
                <tr>
                    <td>Longitude</td>
                    <td><?= $this->item->longitude ?></td>
                </tr>
            </tbody>
        </table>
        <div class="bg tl"><p><?= str_replace(',', '<br>', $this->item->comment) ?></p></div>
        <?= $this->partial('partial/maps', ['maps' => $this->item->maps]) ?>
    </article>
</form>
<footer class="dg c-5">
    <?= $this->paginate($this->page) ?>
    <a href="/roadbook/create">create</a>
    <a href="/roadbook/edit/<?= $this->item->id ?>">edit</a>
    <a href="/roadbook/grid">grid</a>
    <a href="/roadbook/file" class="s-2">select</a>
</footer>
