<a href="<?= $this->url ?>/0" class="tl<?= 0 == $this->page ? ' o25' : '' ?>">&laquo;</a>
<a href="<?= $this->url ?>/<?= $this->prev ?>" class="tl<?= 0 == $this->page ? ' o25' : '' ?>">&lsaquo;</a>
<p class="tc bg0"><?= sprintf('%d / %d', $this->page + 1, $this->pages) ?></p>
<a href="<?= $this->url ?>/<?= $this->next ?>" class="tr<?= $this->page + 1 >= $this->pages ? ' o25' : '' ?>">&rsaquo;</a>
<a href="<?= $this->url ?>/<?= $this->pages - 1 ?>" class="tr<?= $this->page + 1 >= $this->pages ? ' o25' : '' ?>">&raquo;</a>
