<article class="dg c-3">
    <table>
        <tbody>
            <?php foreach ($this->collection as $item): ?>
            <tr>
                <td><?= $item->date ?></td>
                <td><?= $item->region ?></td>
                <td><?= $item->name ?></td>
                <td><?= implode(' ', $item->positionDD) ?></td>
                <td><?= implode(' ', $item->positionDMS) ?></td>
                <td><?= $item->comment ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</article>
