<section id="route">
    <h2>Route</h2>
    <form method="post">
        <table>
            <thead>
            <tr>
                <th>#</th>
                <th>date</th>
                <th>region</th>
                <th>name</th>
                <th>position</th>
                <th>type</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td colspan="5"></td>
                <td>
                    <label style="display:block">
                        <select name="filter[type]">
                            <?php foreach ($this->types as $type => $shown): ?>
                                <option value="<?= $type ?>"><?= sprintf('%s: %d', ucfirst($type), $shown) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </label>
                </td>
                <td>
                    <button type="submit" name="action" value="filter">f</button>
                    <button type="submit" name="action" value="export">x</button>
                </td>
            </tr>
            </tbody>
            <tbody>
            <?php foreach ($this->roadbook as $i => $waypoint): ?>
                <?php if ($this->types[$waypoint->type]): ?>
                    <tr>
                        <td><?= sprintf('%02d', $i) ?></td>
                        <td><?= $waypoint->date ?></td>
                        <td><?= $waypoint->region ?></td>
                        <td><?= $waypoint->name ?></td>
                        <td><?= $waypoint->position ?></td>
                        <td><?= $waypoint->type ?></td>
                        <td>
                            <button type="submit" name="action" value="edit,<?= $waypoint->id ?>">e</button>
                            <button type="submit" name="action" value="delete,<?= $waypoint->id ?>">d</button>
                            <button type="submit" name="action" value="move,<?= $waypoint->id ?>,0">&uarr;</button>
                            <button type="submit" name="action" value="move,<?= $waypoint->id ?>,1">&darr;</button>
                            <button type="submit" name="action" value="view,<?= $waypoint->id ?>">&rarr;</button>
                        </td>
                        <td class="d-rpi-none">
                            <a href="<?= $this->maps->map($waypoint) ?>" class="button" target="_blank">m</a>
                            <a href="<?= $this->maps->direction($this->roadbook->item($i - 1) ?? $waypoint, $waypoint) ?>" class="button" target="_blank">r</a>
                        </td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
            </tbody>
            <tfoot>
            <tr>
                <td>
                    <input type="hidden" name="id" value="<?= $this->selected->id ?>">
                </td>
                <td>
                    <input type="date" name="date" value="<?= $this->selected->date ?>">
                </td>
                <td>
                    <input type="text" name="region" value="<?= $this->selected->region ?>" placeholder="region">
                </td>
                <td>
                    <input type="text" name="name" value="<?= $this->selected->name ?>" placeholder="name">
                </td>
                <td>
                    <input type="text" name="position" value="<?= $this->selected->position ?>" placeholder="position">
                </td>
                <td>
                    <select name="type">
                        <?php foreach (array_keys($this->types) as $type): ?>
                            <option value="<?= $type ?>" <?= $this->selected->type == $type ? ' selected' : '' ?>><?= ucfirst($type) ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td>
                    <button type="submit" name="action" value="save">s</button>
                    <button type="submit" name="action" value="cancel">c</button>
                </td>
            </tr>
            </tfoot>
        </table>
    </form>
</section>